apiVersion: operator.openshift.io/v1alpha1
kind: IstioCSR
metadata:
  name: default
  namespace: istio-csr          # ! Replace this with your preferred namespace name.
  annotations:
    "kubernetes.io/description": "Creating this resource requires the istio-csr tech-preview feature to be enabled, which otherwise has no effect. Please refer to the cert-manager documentation for more information on enabling the istio-csr feature. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process"
spec:
  istioCSRConfig:
    certManager:
      issuerRef:
        name: istio-csr-issuer  # ❗ Replace this with your own Issuer/ClusterIssuer name.
        kind: Issuer            # ❗ Replace this with the created kind, Issuer/ClusterIssuer.
        group: cert-manager.io
    istiodTLSConfig:
      trustDomain: cluster.local
    istio:
      namespace: istio-system   # ! Replace this with your own istio deployed namespace name.
