apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: default
spec:
  isCA: false
  commonName: "sample.dns.name" #❗Replace this with your own DNS name
  secretName: tls-cert
  dnsNames:
  - "sample.dns.name" #❗Replace this with your own DNS name
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
