apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "aos-ci-cd@redhat.com" #❗Replace this with your own email address
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          #❗Replace these with your own values
          accessKeyID: "ACCESS_KEY_ID"
          hostedZoneID: "HOSTED_ZONE_ID"
          region: "AWS_REGION"
          secretAccessKeySecretRef:
            name: "sample-aws-secret"
            key: "access-key"
      selector:
        dnsNames:
        - 'sample.dns.name' #❗Replace this with your own DNS name
