apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cert-manager-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  labels:
    openshift.io/cluster-monitoring: "true"
