apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:operator:cert-manager
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - events
      - configmaps
      - secrets
      - namespaces
      - serviceaccounts
    verbs:
      - list
      - get
      - create
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - get
      - create
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - ClusterRole
      - RoleBinding
      - Role
    verbs:
      - list
      - get
      - create
      - update
      - watch
  - apiGroups:
      - admissionregistration.k8s.io/v1
    resources:
      - MutatingWebhookConfiguration
      - ValidatingWebhookConfiguration
    verbs:
      - list
      - get
      - create
      - update
      - watch