## This file contains Deployment for the operator. Unfortunately, we don't ship the image
## into the OpenShift Quay org. This needs to be fixed shortly
#FIXME: Deploy images to Quay

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: openshift-cert-manager-operator
#  name: cert-manager-operator
#  labels:
#    app: cert-manager-operator
#  annotations:
#    include.release.openshift.io/self-managed-high-availability: "true"
#    include.release.openshift.io/single-node-developer: "true"
#    config.openshift.io/inject-proxy: cert-manager-operator
#    exclude.release.openshift.io/internal-openshift-hosted: "true"
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: cert-manager-operator
#  template:
#    metadata:
#      name: cert-manager-operator
#      labels:
#        app: cert-manager-operator
#      annotations:
#        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
#    spec:
#      serviceAccountName: cert-manager-operator
#      containers:
#      - name: cert-manager-operator
#        image: quay.io/openshift/origin-cert-manager-operator
#        imagePullPolicy: IfNotPresent
#        command: ["/bin/bash", "-ec"]
#        args:
#        - |
#          if [ -s /var/run/configmaps/trusted-ca-bundle/ca-bundle.crt ]; then
#              echo "Copying system trust bundle"
#              cp -f /var/run/configmaps/trusted-ca-bundle/ca-bundle.crt /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
#          fi
#          exec cert-manager-operator start --config=/var/run/configmaps/config/operator-config.yaml --v=2 --terminate-on-files=/var/run/configmaps/trusted-ca-bundle/ca-bundle.crt
#        resources:
#          requests:
#            memory: 200Mi
#            cpu: 20m
#        securityContext:
#          readOnlyRootFilesystem: false # because of the `cp` in args
#        volumeMounts:
#        - mountPath: /var/run/configmaps/config
#          name: config
#        - mountPath: /var/run/secrets/serving-cert
#          name: serving-cert
#        - mountPath: /var/run/configmaps/trusted-ca-bundle
#          name: trusted-ca-bundle
#          readOnly: true
#        - mountPath: /var/run/configmaps/service-ca-bundle
#          name: service-ca-bundle
#          readOnly: true
#        livenessProbe:
#          initialDelaySeconds: 30
#          httpGet:
#            scheme: HTTPS
#            port: 8443
#            path: healthz
#        env:
#        - name: IMAGE_CERT_MANAGER_CONTROLLER
#          value: quay.io/jetstack/cert-manager-controller:v1.4.0
#        - name: IMAGE_CERT_MANAGER_CAINJECTOR
#          value: quay.io/jetstack/cert-manager-cainjector:v1.4.0
#        - name: IMAGE_CERT_MANAGER_WEBHOOK
#          value: quay.io/jetstack/cert-manager-webhook:v1.4.0
#        - name: OPERATOR_IMAGE_VERSION
#          value: "0.0.1-snapshot"
#        - name: POD_NAME
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.name
#        terminationMessagePolicy: FallbackToLogsOnError
#      volumes:
#      - name: config
#        configMap:
#          defaultMode: 440
#          name: cert-manager-operator-config
#      - name: trusted-ca-bundle
#        configMap:
#          name: trusted-ca-bundle
#          optional: true
#      - name: serving-cert
#        secret:
#          secretName: serving-cert
#          optional: true
#      - name: service-ca-bundle
#        configMap:
#          name: service-ca-bundle
#          optional: true
#      nodeSelector:
#        node-role.kubernetes.io/master: ""
#      tolerations:
#      - key: "node-role.kubernetes.io/master"
#        operator: "Exists"
#        effect: "NoSchedule"
#      - key: "node.kubernetes.io/unreachable"
#        operator: "Exists"
#        effect: "NoExecute"
#        tolerationSeconds: 120
#      - key: "node.kubernetes.io/not-ready"
#        operator: "Exists"
#        effect: "NoExecute"
#        tolerationSeconds: 120
